// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7W0ISJG5OPmPkRh5ufwcLimrcqdGzITg',
    appId: '1:80764980308:web:cf6c0908afe5eec9c0b1c1',
    messagingSenderId: '80764980308',
    projectId: 'nolimitedogol-95c3d',
    authDomain: 'nolimitedogol-95c3d.firebaseapp.com',
    storageBucket: 'nolimitedogol-95c3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbmpFv4CUjmdjON1ylVMURzye-u2kltdo',
    appId: '1:80764980308:android:f9a80db4876fe0b4c0b1c1',
    messagingSenderId: '80764980308',
    projectId: 'nolimitedogol-95c3d',
    storageBucket: 'nolimitedogol-95c3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMfC-cEFWDAyL436EptQwT7TFzkBzM-Bc',
    appId: '1:80764980308:ios:1aac4892d93f96cec0b1c1',
    messagingSenderId: '80764980308',
    projectId: 'nolimitedogol-95c3d',
    storageBucket: 'nolimitedogol-95c3d.firebasestorage.app',
    iosClientId: '80764980308-jr33bjl1plsdq00v2o7r76q6dede58ui.apps.googleusercontent.com',
    iosBundleId: 'com.example.mercadodegols',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMfC-cEFWDAyL436EptQwT7TFzkBzM-Bc',
    appId: '1:80764980308:ios:1aac4892d93f96cec0b1c1',
    messagingSenderId: '80764980308',
    projectId: 'nolimitedogol-95c3d',
    storageBucket: 'nolimitedogol-95c3d.firebasestorage.app',
    iosClientId: '80764980308-jr33bjl1plsdq00v2o7r76q6dede58ui.apps.googleusercontent.com',
    iosBundleId: 'com.example.mercadodegols',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7W0ISJG5OPmPkRh5ufwcLimrcqdGzITg',
    appId: '1:80764980308:web:45da8ebdc3d06ce8c0b1c1',
    messagingSenderId: '80764980308',
    projectId: 'nolimitedogol-95c3d',
    authDomain: 'nolimitedogol-95c3d.firebaseapp.com',
    storageBucket: 'nolimitedogol-95c3d.firebasestorage.app',
  );
}
